language: node_js
node_js:
    - '6'
cache:
    directories:
        - node_modules
branches:
    only:
        - master
notifications:
    email:
        on_success: never
        on_failure: always
before_install:
    - npm install -g jshint jscs
before_script:
    - npm prune
script:
    - npm run cover
    - npm run check-coverage
    - npm run lint
after_success:
    - npm run report-coverage
    - npm run semantic-release
