language: node_js
node_js:
    - "6"
cache:
    directories:
        - node_modules
notifications:
    email:
        on_success: never
        on_failure: always
before_script:
    - npm prune
script:
    - npm test
